# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "Getting started"
  link: "/getting-started"
- label: "Bootstrap Template"
  link: "/bootstrap-template"
- label: "Tailwind Template"
  link: "/tailwind-template"
- label: "Configuring Contact Form"
  link: "/contact-form"